import { FacialHairOption, HairStyleOption } from "./types";

export const ART_STYLES: string[] = [
  'Photo-Realistic',
  'Digital Art',
  'Cinematic',
  '3D Model',
  'Anime',
  'Fantasy Art',
  'Vintage Photo',
  'Cyberpunk',
  'Watercolor',
  'Oil Painting'
];

export const UPSCALE_FACTORS: number[] = [2, 4, 8, 16];

export const FACIAL_HAIR_OPTIONS: FacialHairOption[] = ['none', 'add', 'remove'];

export const HAIR_STYLE_OPTIONS: HairStyleOption[] = ['none', 'neat', 'short', 'wavy', 'curly'];

export const translations = {
  en: {
    headerTitle: 'AI Image Enhancer',
    headerPro: 'Pro',
    langSwitch: 'العربية',
    originalImage: 'Original Image',
    uploadTitle: 'Click to upload image',
    uploadSubtitle: 'PNG, JPG, WEBP, or PDF',
    changeImage: 'Change Image',
    controls: 'Controls',
    style: 'Style',
    upscale: 'Upscale',
    facialHair: 'Facial Hair',
    facialHair_none: 'None',
    facialHair_add: 'Add beard & mustache',
    facialHair_remove: 'Remove beard & mustache',
    hairStyle: 'Hair Style',
    hairStyle_none: 'None',
    hairStyle_neat: 'Neat & Combed',
    hairStyle_short: 'Short',
    hairStyle_wavy: 'Wavy',
    hairStyle_curly: 'Curly',
    removeBlemishes: 'Remove Blemishes',
    faceSmoothing: 'Face Smoothing',
    depixelateFace: 'Depixelate Face',
    fillHairGaps: 'Fill Hair Gaps',
    changeClothes: 'Change Clothes',
    changeClothesPlaceholder: 'e.g., black leather jacket',
    changeBackground: 'Change Background',
    changeBackgroundPlaceholder: 'e.g., tropical beach at sunset',
    faceMerge: 'Face Merge',
    faceMergeTooltip: 'Upload a source face image to transfer its skin quality (smoothness, texture) to the face in your original image. Your unique facial features (eyes, nose, mouth, shape) will be preserved.',
    uploadSourceFace: 'Upload Source Face',
    removeSourceFace: 'Remove',
    aiStrength: 'AI Strength',
    aiStrengthTooltip: 'Controls how much creative freedom the AI has. Higher values lead to more artistic and imaginative changes.',
    resemblance: 'Resemblance',
    resemblanceTooltip: 'Controls how closely the result should match the original image\'s composition and subjects.',
    negativePrompt: 'Negative Prompt',
    negativePromptPlaceholder: 'e.g., blurry, text, watermark',
    enhanceButton: 'Enhance Image',
    result: 'Result',
    selectBestResult: 'Select the best result below',
    compareTooltip: 'Press and hold image to see original',
    originalLabel: 'Original',
    print: 'Print',
    downloadPng: 'Download PNG',
    downloadJpeg: 'Download JPEG',
    loadingTitle: 'Enhancing your image...',
    loadingSubtitle: 'The AI is creating 4 different versions for you. This may take a moment.',
    placeholderTitle: 'Your Enhanced Image Appears Here',
    placeholderSubtitle: 'Upload an image and click "Enhance" to begin.',
    errorUpload: 'Please upload an image first.',
    errorEnhance: 'Failed to enhance the image. Please try again.',
    footer: 'Powered by the Gemini API',
    printSettings: 'Print Settings',
    paperSize: 'Paper Size',
    photoSize: 'Photo Size',
    passportPhoto: 'Passport Photo (35x45 mm)',
    idCardPhoto: 'ID Card Photo (2x2 in)',
    custom: 'Custom',
    width: 'Width',
    height: 'Height',
    pagePreview: 'Page Preview',
    photosPerPage: 'photos per page',
    printPage: 'Print Page',
    close: 'Close',
    printImage: 'Print Image',
    gapBetweenPhotos: 'Gap Between Photos',
    layout: 'Layout',
    layout_repeat: 'Repeat Photo',
    layout_single: 'Single Photo',
    layout_contactSheet: 'Contact Sheet',
    layout_grid: 'Grid Layout',
    rows: 'Rows',
    columns: 'Columns',
    resetView: 'Reset View',
    zoomIn: 'Zoom In',
    zoomOut: 'Zoom Out',
  },
  ar: {
    headerTitle: 'محسِّن الصور بالذكاء الاصطناعي',
    headerPro: 'برو',
    langSwitch: 'English',
    originalImage: 'الصورة الأصلية',
    uploadTitle: 'انقر لتحميل صورة',
    uploadSubtitle: 'PNG, JPG, WEBP, أو PDF',
    changeImage: 'تغيير الصورة',
    controls: 'عناصر التحكم',
    style: 'النمط الفني',
    upscale: 'تحسين الدقة',
    facialHair: 'شعر الوجه',
    facialHair_none: 'لا شيء',
    facialHair_add: 'إضافة لحية وشوارب',
    facialHair_remove: 'إزالة اللحية والشوارب',
    hairStyle: 'تصفيف الشعر',
    hairStyle_none: 'لا شيء',
    hairStyle_neat: 'أنيق ومُمشّط',
    hairStyle_short: 'قصير',
    hairStyle_wavy: 'مموج',
    hairStyle_curly: 'مجعد',
    removeBlemishes: 'إزالة الشوائب',
    faceSmoothing: 'تنعيم الوجه',
    depixelateFace: 'إزالة البكسلات من الوجه',
    fillHairGaps: 'سد فراغات الشعر',
    changeClothes: 'تغيير الملابس',
    changeClothesPlaceholder: 'مثال: سترة جلدية سوداء',
    changeBackground: 'تغيير الخلفية',
    changeBackgroundPlaceholder: 'مثال: شاطئ استوائي عند الغروب',
    faceMerge: 'دمج الوجوه',
    faceMergeTooltip: 'قم بتحميل صورة وجه مصدر لنقل جودة بشرته (نعومة، ملمس) إلى الوجه في صورتك الأصلية. سيتم الحفاظ على ملامح وجهك الفريدة (عيون، أنف، فم، شكل).',
    uploadSourceFace: 'تحميل وجه المصدر',
    removeSourceFace: 'إزالة',
    aiStrength: 'قوة الذكاء الاصطناعي',
    aiStrengthTooltip: 'تتحكم في مدى الحرية الإبداعية للذكاء الاصطناعي. القيم الأعلى تؤدي إلى تغييرات فنية ومبتكرة أكثر.',
    resemblance: 'التشابه مع الأصل',
    resemblanceTooltip: 'تتحكم في مدى تطابق النتيجة مع تكوين ومواضيع الصورة الأصلية.',
    negativePrompt: 'التوجيهات السلبية',
    negativePromptPlaceholder: 'مثال: ضبابي، نص، علامة مائية',
    enhanceButton: 'تحسين الصورة',
    result: 'النتيجة',
    selectBestResult: 'اختر النتيجة الأفضل في الأسفل',
    compareTooltip: 'اضغط مع الاستمرار على الصورة لرؤية الأصل',
    originalLabel: 'الأصلية',
    print: 'طباعة',
    downloadPng: 'تنزيل PNG',
    downloadJpeg: 'تنزيل JPEG',
    loadingTitle: 'جاري تحسين صورتك...',
    loadingSubtitle: 'يقوم الذكاء الاصطناعي بإنشاء 4 نسخ مختلفة لك. قد يستغرق هذا بعض الوقت.',
    placeholderTitle: 'صورتك المحسنة ستظهر هنا',
    placeholderSubtitle: 'قم بتحميل صورة وانقر على "تحسين" للبدء.',
    errorUpload: 'يرجى تحميل صورة أولاً.',
    errorEnhance: 'فشل تحسين الصورة. يرجى المحاولة مرة أخرى.',
    footer: 'مدعوم بواسطة Gemini API',
    printSettings: 'إعدادات الطباعة',
    paperSize: 'حجم الورق',
    photoSize: 'حجم الصورة',
    passportPhoto: 'صورة جواز السفر (35x45 مم)',
    idCardPhoto: 'صورة الهوية (2x2 بوصة)',
    custom: 'مخصص',
    width: 'العرض',
    height: 'الارتفاع',
    pagePreview: 'معاينة الصفحة',
    photosPerPage: 'صورة في كل صفحة',
    printPage: 'اطبع الصفحة',
    close: 'إغلاق',
    printImage: 'طباعة صورة',
    gapBetweenPhotos: 'المسافة بين الصور',
    layout: 'التخطيط',
    layout_repeat: 'تكرار الصورة',
    layout_single: 'صورة واحدة',
    layout_contactSheet: 'ورقة الصور المصغرة',
    layout_grid: 'تخطيط الشبكة',
    rows: 'الصفوف',
    columns: 'الأعمدة',
    resetView: 'إعادة تعيين العرض',
    zoomIn: 'تكبير',
    zoomOut: 'تصغير',
  },
};